language: java
jdk: -oraclejdk15
sudo: false

#after_success:
# - bash <(curl -s https://codecov.io/bash)

nitifications:
  email:
    recipients:
      - frowzygleb@gmail.com
    on_success: never
    on_failure: always